cicd 3

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -90,6 +90,12 @@ jobs:
         echo "MySQL did not become ready in time."
         exit 1
 
+    - name: Run Flask Unit Tests
+      run: |
+        echo "Running Flask unit tests..."
+        docker exec flask python -m unittest discover tests
+
+
     # - name: Upload Application Stack Log Artifact
     #   uses: actions/upload-artifact@v4
     #   with:
@@ -99,6 +105,8 @@ jobs:
     #       nginx.log
     #     retention-days: 7
 
+
+
     - name: Teardown
       if: always()
       run: docker-compose -f docker-compose.ci.yml down -v
@@ -107,31 +115,33 @@ jobs:
       if: always()
       run: rm -f app-server/.env
 
-  # full-stack-snort3:
-  #   name: Snort3 Smoke Test
-  #   runs-on: ubuntu-latest
-
-  #   steps:
-  #   - name: Checkout Repo
-  #     uses: actions/checkout@v3
-
-  #   - name: Set up Buildx
-  #     uses: docker/setup-buildx-action@v3
-
-  #   - name: Install Docker Compose
-  #     run: |
-  #       sudo apt-get update
-  #       sudo apt-get install -y docker-compose
     
-  #   - name: Build Snort3 Container (without host network)
-  #     run: |
-  #       docker compose -f snort-compose.yml config > temp.yml
-  #       sed -i '/network_mode/d' temp.yml  # Remove host networking for CI
-  #       docker compose -f temp.yml up -d --build
 
-  #   - name: Check Snort3 is Running
-  #     run: docker ps | grep snort3 || (echo "Snort3 failed to run" && exit 1)
+  full-stack-snort3:
+    name: Snort3 Smoke Test
+    runs-on: ubuntu-latest
 
-  #   - name: Teardown Snort3
-  #     if: always()
-  #     run: docker compose -f temp.yml down -v
+    steps:
+    - name: Checkout Repo
+      uses: actions/checkout@v3
+
+    - name: Set up Buildx
+      uses: docker/setup-buildx-action@v3
+
+    - name: Install Docker Compose
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y docker-compose
+    
+    - name: Build Snort3 Container (without host network)
+      run: |
+        docker compose -f snort-compose.yml config > temp.yml
+        sed -i '/network_mode/d' temp.yml  # Remove host networking for CI
+        docker compose -f temp.yml up -d --build
+
+    - name: Check Snort3 is Running
+      run: docker ps | grep snort3 || (echo "Snort3 failed to run" && exit 1)
+
+    - name: Teardown Snort3
+      if: always()
+      run: docker compose -f temp.yml down -v
