CICD Test #3

diff --git a/.github/workflows/flask-ci.yml b/.github/workflows/flask-ci.yml
--- a/.github/workflows/flask-ci.yml
+++ b/.github/workflows/flask-ci.yml
@@ -31,6 +31,9 @@ jobs:
         SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
         SPLUNK_HEC_URL: ${{ secrets.SPLUNK_HEC_URL }}
         B64_KEY: ${{ secrets.B64_KEY }}
+
+      - name: Follow Container Logs
+      run: docker-compose -f docker-compose.ci.yml logs -f --no-color
       
     - name: Decode Firebase Key and Export Path
       run: |
@@ -38,11 +41,13 @@ jobs:
         echo "Key decoded and ready to use"
         cat /tmp/test.json
 
+    - name: debugger
+      run: docker exec flask -rm
     # - name: Run Flask Test
     #   run: docker exec flask python /app/tests/test_basic_nonginx.py
 
     - name: Check Flask via NGINX
-      run: curl -s --fail http://localhost:80/login || (echo "Flask app failed!" && exit 1)
+      run: curl -v --fail http://localhost:80/login || (echo "Flask app failed!" && exit 1)
 
     # This shit too strict LMAO
     # - name: Lint Flask App in Container
