CI test #1

diff --git a/.github/workflows/flask-ci.yml b/.github/workflows/flask-ci.yml
--- a/.github/workflows/flask-ci.yml
+++ b/.github/workflows/flask-ci.yml
@@ -31,7 +31,7 @@ jobs:
       run: docker exec flask python /app/tests/test_basic_nonginx.py
 
     - name: Check Flask via NGINX
-      run: curl -s --fail http://localhost:80 || (echo "Flask app failed!" && exit 1)
+      run: curl -s --fail http://localhost:80/login || (echo "Flask app failed!" && exit 1)
 
     # This shit too strict LMAO
     # - name: Lint Flask App in Container
