CI refining NGINX

diff --git a/.github/workflows/flask-ci.yml b/.github/workflows/flask-ci.yml
--- a/.github/workflows/flask-ci.yml
+++ b/.github/workflows/flask-ci.yml
@@ -25,10 +25,13 @@ jobs:
         sudo apt-get install -y docker-compose
 
     - name: Build Flask Container
-      run: docker-compose -f docker-compose.ci.yml up -d --build flask mysqldb 
+      run: docker-compose -f docker-compose.ci.yml up -d --build flask mysqldb nginx
 
-    - name: Run Simple Flask Test
+    - name: Run Flask Test
       run: docker exec flask python /app/tests/test_basic_nonginx.py
+
+    - name: Check Flask via NGINX
+      run: curl -s --fail http://localhost:80 || (echo "Flask app failed!" && exit 1)
 
     # This shit too strict LMAO
     # - name: Lint Flask App in Container
